version: '3.7'
services:
  mqtt5:
    image: eclipse-mosquito
    container_name: mqtt5
    ports:
      - '1885:1885' #mqtt port
      - '9005:9005' #mqtt port for websockets
    volumes:
      - ./config:mosquitto/config:rw
      - ./data/mosquitto/data:rw
      - ./log/mosquitto/log:rw
    restart: unless-stopped

# Volumes for mapping data, config and log:

volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt5-network